// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"ja_JP": &dictionary{index: ja_JPIndex, data: ja_JPData},
		"ru_RU": &dictionary{index: ru_RUIndex, data: ru_RUData},
		"tr_TR": &dictionary{index: tr_TRIndex, data: tr_TRData},
		"zh_CN": &dictionary{index: zh_CNIndex, data: zh_CNData},
		"zh_HK": &dictionary{index: zh_HKIndex, data: zh_HKData},
		"zh_TW": &dictionary{index: zh_TWIndex, data: zh_TWData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Address":    27,
	"Appearance": 21,
	"Are you sure you want to delete all received files?": 7,
	"Cancel":                 12,
	"Delete All":             6,
	"Disable Compression":    38,
	"Disable Local":          31,
	"Disable Multiplexing":   37,
	"Download":               5,
	"Enable Debug Log":       3,
	"Enter code to download": 4,
	"Export full log":        1,
	"Font":                   24,
	"Force Local Only":       32,
	"Hash Algorithm":         36,
	"Language":               22,
	"License Info":           0,
	"Logo":                   25,
	"Multicast Address":      33,
	"Network Local":          30,
	"PAKE Curve":             35,
	"Password":               29,
	"Pick a file to send":    15,
	"Ports":                  28,
	"Receive":                14,
	"Receive Code":           13,
	"Receive cancelled.":     8,
	"Received":               11,
	"Receiving file":         9,
	"Relay":                  26,
	"Saved all files to":     2,
	"Send":                   16,
	"Send Code":              19,
	"Send cancelled.":        10,
	"Sending file":           17,
	"Sent file":              18,
	"Show / Hide":            20,
	"Theme":                  23,
	"Transfer Options":       34,
	"Upload Speed Throttle":  39,
}

var en_USIndex = []uint32{ // 41 elements
	// Entry 0 - 1F
	0x00000000, 0x0000000d, 0x0000001d, 0x00000030,
	0x00000041, 0x00000058, 0x00000061, 0x0000006c,
	0x000000a0, 0x000000b3, 0x000000c2, 0x000000d2,
	0x000000db, 0x000000e2, 0x000000ef, 0x000000f7,
	0x0000010b, 0x00000110, 0x0000011d, 0x00000127,
	0x00000131, 0x0000013d, 0x00000148, 0x00000151,
	0x00000157, 0x0000015c, 0x00000161, 0x00000167,
	0x0000016f, 0x00000175, 0x0000017e, 0x0000018c,
	// Entry 20 - 3F
	0x0000019a, 0x000001ab, 0x000001bd, 0x000001ce,
	0x000001d9, 0x000001e8, 0x000001fd, 0x00000211,
	0x00000227,
} // Size: 188 bytes

const en_USData string = "" + // Size: 551 bytes
	"\x02License Info\x02Export full log\x02Saved all files to\x02Enable Debu" +
	"g Log\x02Enter code to download\x02Download\x02Delete All\x02Are you sur" +
	"e you want to delete all received files?\x02Receive cancelled.\x02Receiv" +
	"ing file\x02Send cancelled.\x02Received\x02Cancel\x02Receive Code\x02Rec" +
	"eive\x02Pick a file to send\x02Send\x02Sending file\x02Sent file\x02Send" +
	" Code\x02Show / Hide\x02Appearance\x02Language\x02Theme\x02Font\x02Logo" +
	"\x02Relay\x02Address\x02Ports\x02Password\x02Network Local\x02Disable Lo" +
	"cal\x02Force Local Only\x02Multicast Address\x02Transfer Options\x02PAKE" +
	" Curve\x02Hash Algorithm\x02Disable Multiplexing\x02Disable Compression" +
	"\x02Upload Speed Throttle"

var ja_JPIndex = []uint32{ // 41 elements
	// Entry 0 - 1F
	0x00000000, 0x00000016, 0x0000003b, 0x0000006a,
	0x00000089, 0x000000b4, 0x000000c7, 0x000000d7,
	0x00000126, 0x00000151, 0x0000016a, 0x00000195,
	0x000001a8, 0x000001b8, 0x000001c8, 0x000001cf,
	0x000001f1, 0x000001f8, 0x00000211, 0x00000233,
	0x00000243, 0x00000256, 0x0000025d, 0x00000264,
	0x0000026e, 0x0000027b, 0x00000282, 0x0000028c,
	0x00000299, 0x000002a3, 0x000002b3, 0x000002d2,
	// Entry 20 - 3F
	0x000002fd, 0x0000032e, 0x00000350, 0x00000366,
	0x00000371, 0x00000390, 0x000003ac, 0x000003bf,
	0x000003e1,
} // Size: 188 bytes

const ja_JPData string = "" + // Size: 993 bytes
	"\x02ライセンス情報\x02完全なログをエクスポート\x02すべてのファイルを保存しました:\x02デバッグログを有効化\x02コードを入力し" +
	"てダウンロード\x02ダウンロード\x02すべて削除\x02すべての受信したファイルを削除してもよろしいですか？\x02受信がキャンセルされ" +
	"ました。\x02ファイルを受信中\x02送信がキャンセルされました。\x02受信しました\x02キャンセル\x02受信コード\x02受信" +
	"\x02ファイルを選択して送信\x02送信\x02ファイルを送信中\x02ファイルを送信しました\x02送信コード\x02表示 / 非表示" +
	"\x02外観\x02言語\x02テーマ\x02フォント\x02ロゴ\x02リレー\x02アドレス\x02ポート\x02パスワード\x02ローカル" +
	"ネットワーク\x02ローカルネットワークを無効化\x02ローカルネットワークのみ使用する\x02マルチキャストアドレス\x02転送オプション" +
	"\x02PAKE曲線\x02ハッシュアルゴリズム\x02多重化を無効にする\x02圧縮を無効化\x02アップロード速度の制限"

var ru_RUIndex = []uint32{ // 41 elements
	// Entry 0 - 1F
	0x00000000, 0x0000002e, 0x0000004e, 0x00000069,
	0x00000084, 0x000000c3, 0x000000d4, 0x000000ea,
	0x00000149, 0x0000016a, 0x00000179, 0x00000196,
	0x000001a5, 0x000001b6, 0x000001c3, 0x000001ce,
	0x000001e4, 0x000001ed, 0x000001fc, 0x00000209,
	0x00000216, 0x00000236, 0x0000023d, 0x00000246,
	0x0000024f, 0x0000025a, 0x00000269, 0x0000027c,
	0x00000287, 0x00000292, 0x0000029f, 0x000002a8,
	// Entry 20 - 3F
	0x000002be, 0x000002cf, 0x000002dc, 0x000002e7,
	0x000002f9, 0x00000309, 0x00000337, 0x0000034b,
	0x0000035a,
} // Size: 188 bytes

const ru_RUData string = "" + // Size: 858 bytes
	"\x02Лицензионная информация\x02Сохранить журнал\x02Сохранил всё в\x02Жур" +
	"налировать\x02Секрет должен быть больше 5 знаков\x02Получить\x02Удалить" +
	" всё\x02Вы уверены что хотите удалить все полученные файлы?\x02Отмена по" +
	"лучения.\x02Получаю\x02Отмена посылки.\x02Получил\x02Отменить\x02Секрет" +
	"\x02Взять\x02Что послать\x02Дать\x02Посылаю\x02Послал\x02Секрет\x02Показ" +
	"ать / Скрыть\x02Вид\x02Язык\x02Тема\x02Шрифт\x02Логотип\x02Посредник" +
	"\x02Адрес\x02Порты\x02Пароль\x02сеть\x02Не локально\x02Локально\x02Групп" +
	"а\x02Обмен\x02Кривая PAKE\x02Тип хеша\x02Без мультиплексирования\x02Без" +
	" сжатия\x02Медлить"

var tr_TRIndex = []uint32{ // 41 elements
	// Entry 0 - 1F
	0x00000000, 0x00000011, 0x00000027, 0x00000049,
	0x00000074, 0x0000008f, 0x00000096, 0x000000a4,
	0x000000e1, 0x000000f4, 0x00000105, 0x0000011d,
	0x00000126, 0x0000012d, 0x00000134, 0x00000137,
	0x00000155, 0x0000015d, 0x00000171, 0x00000183,
	0x0000018f, 0x0000019f, 0x000001aa, 0x000001ae,
	0x000001b3, 0x000001be, 0x000001c3, 0x000001c9,
	0x000001cf, 0x000001d7, 0x000001de, 0x000001e8,
	// Entry 20 - 3F
	0x00000209, 0x00000222, 0x0000023d, 0x00000253,
	0x00000260, 0x00000272, 0x00000296, 0x000002bd,
	0x000002da,
} // Size: 188 bytes

const tr_TRData string = "" + // Size: 730 bytes
	"\x02Lisans Bilgileri\x02Tam logu dışa aktar\x02Tüm dosyalar şuraya kayde" +
	"dildi:\x02Hata Ayıklama Günlüğünü Etkinleştir\x02İndirmek için kodu giri" +
	"n\x02İndir\x02Tümünü Sil\x02Tüm alınan dosyaları silmek istediğinizden e" +
	"min misiniz?\x02Alma iptal edildi.\x02Dosya alınıyor\x02Gönderme iptal e" +
	"dildi.\x02Alındı\x02İptal\x02Kod Al\x02Al\x02Gönderilecek dosyayı seçin" +
	"\x02Gönder\x02Dosya gönderiliyor\x02Dosya gönderildi\x02Kod Gönder\x02Gö" +
	"ster / Gizle\x02Görünüm\x02Dil\x02Tema\x02Yazı Tipi\x02Logo\x02Röle\x02A" +
	"dres\x02Portlar\x02Şifre\x02Yerel Ağ\x02Yerel Ağı Devre Dışı Bırak\x02Sa" +
	"dece Yerel Ağı Zorla\x02Çok Noktaya Yayın Adresi\x02Transfer Seçenekleri" +
	"\x02PAKE Eğrisi\x02Hash Algoritması\x02Çoğullamayı Devre Dışı Bırak\x02S" +
	"ıkıştırmayı Devre Dışı Bırak\x02Yükleme Hızını Sınırla"

var zh_CNIndex = []uint32{ // 41 elements
	// Entry 0 - 1F
	0x00000000, 0x00000010, 0x00000023, 0x0000003c,
	0x0000004f, 0x00000062, 0x00000069, 0x00000076,
	0x000000a1, 0x000000b4, 0x000000c7, 0x000000da,
	0x000000e4, 0x000000eb, 0x000000f5, 0x000000fc,
	0x00000115, 0x0000011c, 0x0000012f, 0x0000013f,
	0x00000149, 0x00000157, 0x0000015e, 0x00000165,
	0x0000016c, 0x00000173, 0x0000017a, 0x00000181,
	0x00000188, 0x0000018f, 0x00000196, 0x000001a3,
	// Entry 20 - 3F
	0x000001b6, 0x000001cc, 0x000001d9, 0x000001e6,
	0x000001f1, 0x000001fe, 0x00000211, 0x0000021e,
	0x00000231,
} // Size: 188 bytes

const zh_CNData string = "" + // Size: 561 bytes
	"\x02许可证信息\x02导出完整日志\x02所有文件已保存至\x02启用调试日志\x02输入下载代码\x02下载\x02全部删除\x02确定要" +
	"删除所有接收的文件吗？\x02接收已取消。\x02正在接收文件\x02发送已取消。\x02已接收\x02取消\x02接收码\x02接收" +
	"\x02选择要发送的文件\x02发送\x02正在发送文件\x02已发送文件\x02发送码\x02显示/隐藏\x02外观\x02语言\x02主题" +
	"\x02字体\x02徽标\x02中继\x02地址\x02端口\x02密码\x02本地网络\x02禁用本地网络\x02强制仅本地网络\x02组播地" +
	"址\x02传输选项\x02PAKE曲线\x02哈希算法\x02禁用多路复用\x02禁用压缩\x02上传速度限制"

var zh_HKIndex = []uint32{ // 41 elements
	// Entry 0 - 1F
	0x00000000, 0x00000010, 0x00000023, 0x0000003c,
	0x0000004f, 0x00000062, 0x00000069, 0x00000076,
	0x000000a1, 0x000000b4, 0x000000c7, 0x000000da,
	0x000000e4, 0x000000eb, 0x000000f5, 0x000000fc,
	0x00000115, 0x0000011c, 0x0000012f, 0x0000013f,
	0x00000149, 0x00000157, 0x0000015e, 0x00000165,
	0x0000016c, 0x00000173, 0x0000017a, 0x00000181,
	0x00000188, 0x0000018c, 0x00000193, 0x000001a0,
	// Entry 20 - 3F
	0x000001b3, 0x000001cc, 0x000001df, 0x000001ec,
	0x000001f7, 0x00000207, 0x0000021a, 0x00000227,
	0x0000023a,
} // Size: 188 bytes

const zh_HKData string = "" + // Size: 570 bytes
	"\x02許可證資訊\x02匯出完整記錄\x02所有檔案已儲存至\x02啟用偵錯記錄\x02輸入下載代碼\x02下載\x02全部刪除\x02確定要" +
	"刪除所有接收的檔案嗎？\x02接收已取消。\x02正在接收檔案\x02傳送已取消。\x02已接收\x02取消\x02接收碼\x02接收" +
	"\x02選擇要傳送的檔案\x02傳送\x02正在傳送檔案\x02已傳送檔案\x02傳送碼\x02顯示/隱藏\x02外觀\x02語言\x02主題" +
	"\x02字型\x02標誌\x02轉發\x02地址\x02埠\x02密碼\x02本地網絡\x02停用本地網絡\x02強制僅限本地網絡\x02多點傳" +
	"送位址\x02傳輸選項\x02PAKE曲線\x02雜湊演算法\x02停用多工處理\x02停用壓縮\x02上傳速度限制"

var zh_TWIndex = []uint32{ // 41 elements
	// Entry 0 - 1F
	0x00000000, 0x0000000d, 0x00000020, 0x00000039,
	0x0000004c, 0x0000005f, 0x00000066, 0x00000073,
	0x0000009e, 0x000000b1, 0x000000c4, 0x000000d7,
	0x000000e1, 0x000000e8, 0x000000f2, 0x000000f9,
	0x00000112, 0x00000119, 0x0000012c, 0x0000013c,
	0x00000146, 0x00000154, 0x0000015b, 0x00000162,
	0x00000169, 0x00000170, 0x00000177, 0x0000017e,
	0x00000185, 0x00000189, 0x00000190, 0x0000019d,
	// Entry 20 - 3F
	0x000001b0, 0x000001c9, 0x000001dc, 0x000001e9,
	0x000001f4, 0x00000204, 0x00000217, 0x00000224,
	0x00000237,
} // Size: 188 bytes

const zh_TWData string = "" + // Size: 567 bytes
	"\x02授權資訊\x02匯出完整記錄\x02所有檔案已儲存至\x02啟用偵錯記錄\x02輸入下載代碼\x02下載\x02全部刪除\x02確定要刪" +
	"除所有接收的檔案嗎？\x02接收已取消。\x02正在接收檔案\x02傳送已取消。\x02已接收\x02取消\x02接收碼\x02接收\x02" +
	"選擇要傳送的檔案\x02傳送\x02正在傳送檔案\x02已傳送檔案\x02傳送碼\x02顯示/隱藏\x02外觀\x02語言\x02主題" +
	"\x02字型\x02標誌\x02轉發\x02位址\x02埠\x02密碼\x02本地網路\x02停用本地網路\x02強制僅限本地網路\x02多點傳" +
	"送位址\x02傳輸選項\x02PAKE曲線\x02雜湊演算法\x02停用多工處理\x02停用壓縮\x02上傳速度限制"

	// Total table size 6146 bytes (6KiB); checksum: 10D9EC35
