# .github/workflows/build-platform.yml
name: Build Platform

on:
  workflow_call:
    inputs:
      platform_name:
        required: true
        type: string
      runs_on:
        required: true
        type: string # e.g., "ubuntu-latest", "macos-latest", "windows-latest"
      build_script:
        required: true
        type: string # Bash script to run for building
      artifact_name:
        required: true
        type: string
      artifact_path:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.runs_on }}
    
    steps:
      - name: Checkout repository (to access local actions)
        uses: actions/checkout@v4
        with:
            path: .

      - name: Setup and Checkout
        uses: ./.github/actions/setup-and-checkout

      - name: Execute build script
        run: ${{ inputs.build_script }}
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: ${{ inputs.artifact_path }}
          retention-days: 7
          if-no-files-found: error